import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    globals: true,
    include: [
      'src/auth.test.ts',
      'src/config.test.ts',
      'src/agents/base.test.ts',
      'src/agents/curator.test.ts',
      'src/agents/costModel.test.ts',
      'src/agents/director.test.ts',
      'src/agents/scribe.test.ts',
      'src/agents/graphs/forgeGraph.test.ts',
      'src/agents/graphs/pipelines/forge.test.ts',
      'src/agents/graphs/masContract.test.ts',
      'src/agents/graphs/nodes.test.ts',
      'src/agents/toolAccess.test.ts',
      'src/db/postgresMigrations.test.ts',
      'src/db/rlsRestrictedRole.test.ts',
      'src/db/tenantScope.test.ts',
      'src/prompts/expander.test.ts',
      'src/prompts/promptSecurity.test.ts',
      'src/prompts/shared.test.ts',
      'src/prompts/worldStyleGating.test.ts',
      'src/providers/anthropic.test.ts',
      'src/providers/safety.test.ts',
      'src/routes/articleTypes.test.ts',
      'src/routes/agents.cost.test.ts',
      'src/routes/postgresRoutes.test.ts',
      'src/services/archivist.postgres.test.ts',
      'src/services/postgresCore.test.ts',
      'src/tools/context.search.postgres.test.ts',
    ],
    testTimeout: 10000,
  },
});
